# --- This playbook is executed for EVERY test machine ---
- hosts: "*"
  become: yes
  tasks:
  # 2 MINUTE WAIT (FOR APT TO BE UNLOCKED)
  - name: Pause for proper system setup
    pause:
      minutes: 2
  # APT UPDATE AND UPGRADE (???)
  - name: Update apt packages list
    apt:
      update_cache: yes
      upgrade: yes
      cache_valid_time: 86400 #One day    
  # INSTALL QEMU GUEST AGENT (for communication between VM and VE)
  - name: install qemu-guest-agent
    apt:
      name: qemu-guest-agent
      state: present
  - name: make sure qemu-guest-agent is running
    systemd:
      state: started
      name: qemu-guest-agent
  # SET TIMEZONE TO VIENNA
  - name: set time zone
    community.general.timezone:
      name: Europe/Vienna